### ISSUE TITLE
Conversation bubbles are not piled up

### ISSUE THREAD

**Issue by jatarifa** [cmdotcom/text-sdk-java#13]
The returned value should be assigned again to the `newArr` variable.

https://github.com/cmdotcom/text-sdk-java/blob/de55914a50216de6442528ae3621df65f47b6b0c/src/main/java/com/cmtelecom/text/sdk/models/multichannel/RichContent.java#L40

The same happens with Suggestions

**Comment by EnessenE** [comment]
Apologies for the _very_ late response! We will test and resolve this soon
