### ISSUE TITLE
java.lang.NoClassDefFoundError: com/cmtelecom/text/sdk/MessagingClient

### ISSUE THREAD

**Issue by AdinhLux** [cmdotcom/text-sdk-java#15]
Greetings,

Having downloaded your project, I ran `mvn clean install` to generate the jar.

Then in my project I set the pom.xml with the following configuration :

        <dependency>
            <groupId>com.github.cmdotcom</groupId>
            <artifactId>text-sdk-java</artifactId>
            <version>1.3-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

The compilation was successful but when running App, I got this error : java.lang.NoClassDefFoundError ( when instantiating **MessagingClient** )

Do you have any ideas what was wrong with my configuration ?

I just wrote 2 lines

        MessagingClient client = new MessagingClient(cmToken);
        client.sendTextMessage(mailBody, cmFrom, new String[]{subject});

I'm using Java 8

**Comment by EnessenE** [comment]
Apologies for the very late response. We will soon look into making the package available in a maven repository while we are doing this we will try to replicate this.

**Comment by EnessenE** [comment]
I wasn't able to replicate this but its probarly related to the .jar file setup, we would recommend you install the latest version through maven central and try again:

```xml
        <dependency>
            <groupId>com.cm</groupId>
            <artifactId>text-sdk</artifactId>
            <version>2.0</version>
        </dependency>
```
Do feel free to create a new issue if this re-appears
